# Generated by Django 4.1.7 on 2023-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('secure_key', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('pid', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Tractor', 'Tractor'), ('Auto', 'Auto'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Van', 'Van'), ('Vehicle', 'Vehicle')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='productimages')),
                ('secure_key', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=100)),
                ('sign_email', models.EmailField(max_length=100, unique=True)),
                ('sign_password', models.CharField(max_length=100)),
                ('sign_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_query', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contactus_data',
            },
        ),
    ]
